/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imgui;

import incomemonitor.*;
import java.awt.Component;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author matthewstokes
 */
public class IMGui extends javax.swing.JFrame {
    Accountant accountant = Accountant.getAccountant();
    /**
     * Creates new form IMGui
     */
    public IMGui() {
        initComponents();
    }
    
    /**
     * creates a new Creditor object.
     */
    private void addCreditor(){
        try{
            accountant.addCreditor(addCreditorNameField.getText(),
                Integer.parseInt((String)addCreditorPaymentDateComboBox.getSelectedItem()),
                Double.parseDouble(addCreditorPaymentDueField.getText()),
                Double.parseDouble(addCreditorBalanceDueField.getText()));
            updateCreditorList();
        }
        catch (Exception e)
        {
            System.out.println(e); //need to give user output of incorrect entry!
        }
    }
    
    /**
     * Updates the remove creditor list.
     */
    private void updateCreditorList(){
        removeCreditorListBox.setListData(accountant.getCreditors().toArray());
    }
    
    /**
     * Clears the input fields for add creditor.
     */
    private void clearFields(){
        addCreditorNameField.setText("");
        addCreditorPaymentDateComboBox.setSelectedIndex(0);
        addCreditorPaymentDueField.setText("");
        addCreditorBalanceDueField.setText("");
    }
    
    /**
     * Removes a creditor from the list of creditors.
     */
    private void removeCreditor(){
        accountant.removeCreditor((Creditor)removeCreditorListBox.getSelectedValue());
    }
    
    /**
     * populates the summary table
     */
    private void updateTable(){
      
        String[] columnNames = new String[summaryTable.getColumnCount()];
        for (int i = 0; i < summaryTable.getColumnCount(); i++){
            columnNames[i] = (String)summaryTable.getColumnName(i);
        }        
       
        Object[][] data = new Object[accountant.getStatusesTrue()][summaryTable.getColumnCount()];
        int counter = 0;
        System.out.println(accountant.getStatusesTrue());
        for (Creditor a : accountant.getCreditors()){
            if (a.getStatus()){
                data[counter][0] = (a.getName());
                data[counter][1] = (a.getDate());
                data[counter][2] = (a.getAmount());
                data[counter][3] = (a.getBalance());
                counter++;
            }
        }
        
        //final JTable table = new JTable(data, columnNames);
        summaryTable.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
        summaryTable.setFillsViewportHeight(true);
    }
    
    private void populatePayeeList(){
        addPaymentListBox.setModel(new DefaultComboBoxModel());
        for (Creditor aCreditor : accountant.getCreditors()){
            if (!aCreditor.getStatus()){
                addPaymentListBox.addItem(aCreditor);
            }
        }
        System.out.println(accountant.getCreditors());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        summaryTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addPaymentButton = new javax.swing.JButton();
        addPaymentListBox = new javax.swing.JComboBox();
        incomeTab = new javax.swing.JPanel();
        creditorTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        addCreditorAddButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addCreditorNameField = new javax.swing.JTextField();
        addCreditorPaymentDueField = new javax.swing.JTextField();
        addCreditorBalanceDueField = new javax.swing.JTextField();
        addCreditorPaymentDateComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        removeCreditorRemoveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        removeCreditorListBox = new javax.swing.JList();
        statsTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtual Accountant");

        homeTab.setBorder(javax.swing.BorderFactory.createTitledBorder("Summary"));
        homeTab.setName(""); // NOI18N
        homeTab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homeTabComponentShown(evt);
            }
        });

        summaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Creditor", "Due Date", "Payment Due", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(summaryTable);

        jLabel1.setText("Add Payment");

        addPaymentButton.setText("Add");
        addPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentButtonActionPerformed(evt);
            }
        });

        addPaymentListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentListBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addPaymentListBox, 0, 226, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPaymentButton)
                        .addGap(28, 28, 28))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPaymentListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPaymentButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 229, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", homeTab);

        javax.swing.GroupLayout incomeTabLayout = new javax.swing.GroupLayout(incomeTab);
        incomeTab.setLayout(incomeTabLayout);
        incomeTabLayout.setHorizontalGroup(
            incomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        incomeTabLayout.setVerticalGroup(
            incomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Income", incomeTab);

        creditorTab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                creditorTabComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Creditor"));

        addCreditorAddButton.setText("Add");
        addCreditorAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCreditorAddButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel5.setText("Payment Date");

        jLabel6.setText("Payment Due");

        jLabel7.setText("Balance Due");

        addCreditorPaymentDateComboBox.setToolTipText("");
        addCreditorPaymentDateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCreditorPaymentDateComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCreditorAddButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addCreditorPaymentDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addCreditorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addCreditorPaymentDueField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addCreditorBalanceDueField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addCreditorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addCreditorPaymentDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addCreditorPaymentDueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addCreditorBalanceDueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCreditorAddButton)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove Creditor"));

        removeCreditorRemoveButton.setText("Remove");
        removeCreditorRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCreditorRemoveButtonActionPerformed(evt);
            }
        });

        removeCreditorListBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(removeCreditorListBox);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeCreditorRemoveButton)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(removeCreditorRemoveButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout creditorTabLayout = new javax.swing.GroupLayout(creditorTab);
        creditorTab.setLayout(creditorTabLayout);
        creditorTabLayout.setHorizontalGroup(
            creditorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditorTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        creditorTabLayout.setVerticalGroup(
            creditorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditorTabLayout.createSequentialGroup()
                .addGroup(creditorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Creditors", creditorTab);

        javax.swing.GroupLayout statsTabLayout = new javax.swing.GroupLayout(statsTab);
        statsTab.setLayout(statsTabLayout);
        statsTabLayout.setHorizontalGroup(
            statsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        statsTabLayout.setVerticalGroup(
            statsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stats", statsTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setBounds(0, 0, 907, 433);
    }// </editor-fold>//GEN-END:initComponents

    private void addCreditorAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCreditorAddButtonActionPerformed
        addCreditor();
        clearFields();
    }//GEN-LAST:event_addCreditorAddButtonActionPerformed

    private void creditorTabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_creditorTabComponentShown
        for (String days : accountant.getDOM()){
            addCreditorPaymentDateComboBox.addItem(days); //set to collection of days in current month
        }
        updateCreditorList();
        clearFields();
    }//GEN-LAST:event_creditorTabComponentShown

    private void removeCreditorRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCreditorRemoveButtonActionPerformed
        removeCreditor();
        updateCreditorList();
    }//GEN-LAST:event_removeCreditorRemoveButtonActionPerformed

    private void homeTabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homeTabComponentShown
        updateTable();
        populatePayeeList();
    }//GEN-LAST:event_homeTabComponentShown

    private void addPaymentListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentListBoxActionPerformed
        // TODO add your handling code here
        //Call populatePayeeList here:
    }//GEN-LAST:event_addPaymentListBoxActionPerformed

    private void addPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentButtonActionPerformed
        // TODO add your handling code for adding payment:
        if (addPaymentListBox.getSelectedItem() != null){
            Creditor selectedCreditor = (Creditor)addPaymentListBox.getSelectedItem();
            if (!selectedCreditor.getStatus()){
                accountant.changeStatus(selectedCreditor);
            }
            populatePayeeList();
            updateTable();
        }
    }//GEN-LAST:event_addPaymentButtonActionPerformed

    private void addCreditorPaymentDateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCreditorPaymentDateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCreditorPaymentDateComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCreditorAddButton;
    private javax.swing.JTextField addCreditorBalanceDueField;
    private javax.swing.JTextField addCreditorNameField;
    private javax.swing.JComboBox addCreditorPaymentDateComboBox;
    private javax.swing.JTextField addCreditorPaymentDueField;
    private javax.swing.JButton addPaymentButton;
    private javax.swing.JComboBox addPaymentListBox;
    private javax.swing.JPanel creditorTab;
    private javax.swing.JPanel homeTab;
    private javax.swing.JPanel incomeTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList removeCreditorListBox;
    private javax.swing.JButton removeCreditorRemoveButton;
    private javax.swing.JPanel statsTab;
    private javax.swing.JTable summaryTable;
    // End of variables declaration//GEN-END:variables
}
